-- Restaurant info from the menu CDN: legal entity (colophon), contact, cuisines, opening times.
with src as {{ raw_entity('lieferando', 'menu_manifest') }}
select
  observation_id, run_id, fetched_at,
  payload ->> 'RestaurantId'                               as platform_id,
  natural_key                                              as slug,
  payload ->> 'MenuVersion'                                as menu_version,
  (payload ->> 'MessageSentTimestamp')::timestamptz        as menu_published_at,
  {{ clean_text("payload #>> '{RestaurantInfo,Name}'") }}  as name,
  {{ clean_text("payload #>> '{RestaurantInfo,Description}'") }} as description,
  {{ clean_text("payload #>> '{RestaurantInfo,Location,Address}'") }} as address_line,
  payload #>> '{RestaurantInfo,Location,PostCode}'         as postcode,
  payload #>> '{RestaurantInfo,Location,City}'             as city,
  (payload #>> '{RestaurantInfo,Location,Latitude}')::float8  as lat,
  (payload #>> '{RestaurantInfo,Location,Longitude}')::float8 as lon,
  nullif(payload #>> '{RestaurantInfo,AllergenPhoneNumber}', '') as phone_raw,
  {{ phone_e164("nullif(payload #>> '{RestaurantInfo,AllergenPhoneNumber}', '')") }} as phone,
  {{ clean_text("payload #>> '{RestaurantInfo,Colophon,RestaurantName}'") }} as legal_name,
  {{ clean_text("payload #>> '{RestaurantInfo,Colophon,LegalRepresentative}'") }} as legal_representative,
  nullif(regexp_replace(upper(payload #>> '{RestaurantInfo,Colophon,VatNumber}'), '[^A-Z0-9]', '', 'g'), '') as vat_number,
  {{ clean_text("payload #>> '{RestaurantInfo,Colophon,LegalAddress,Address}'") }} as legal_street,
  payload #>> '{RestaurantInfo,Colophon,LegalAddress,PostCode}' as legal_postcode,
  payload #>> '{RestaurantInfo,Colophon,LegalAddress,City}' as legal_city,
  (payload #>> '{RestaurantInfo,IsHalal}')::boolean        as is_halal,
  payload #>> '{RestaurantInfo,StoreFrontType}'            as storefront_type,
  (payload #>> '{RestaurantInfo,NewUntilDate}')::timestamptz as new_until,
  (payload #>> '{RestaurantInfo,IsOffline}')::boolean      as is_offline,
  ops.jarr(payload #> '{RestaurantInfo,CuisineTypes}') as cuisines,
  payload #> '{RestaurantInfo,RestaurantOpeningTimes}'     as opening_times,
  payload #>> '{RestaurantInfo,LogoUrl}'                   as logo_url,
  payload #>> '{RestaurantInfo,ShareableLink}'             as share_url,
  payload -> 'Menus'                                       as menus,
  payload                                                  as attributes
from src
