-- Venue page: legal entity, contact, opening times, ratings, fee structure.
with src as {{ raw_entity('wolt', 'venue_static') }}
select
  observation_id, run_id, fetched_at,
  payload #>> '{venue,id}'                                 as platform_id,
  natural_key                                              as slug,
  {{ clean_text("payload #>> '{venue,name}'") }}           as name,
  {{ clean_text("payload #>> '{venue,address}'") }}        as address_line,
  nullif(payload #>> '{venue,post_code}', '')              as postcode,
  nullif(payload #>> '{venue,city}', '')                   as city,
  nullif(payload #>> '{venue,phone}', '')                  as phone_raw,
  {{ phone_e164("nullif(payload #>> '{venue,phone}', '')") }} as phone,
  {{ clean_url("nullif(payload #>> '{venue,website}', '')") }} as website,
  {{ clean_text("payload #>> '{venue,description}'") }}    as description,
  nullif(payload #>> '{venue,brand_name}', '')             as brand_name,
  nullif(payload #>> '{venue,brand_slug}', '')             as brand_slug,
  payload #>> '{venue,product_line}'                       as product_line,
  payload #>> '{venue,share_url}'                          as share_url,
  {{ clean_text("payload #>> '{venue,merchant,name}'") }}  as legal_name,
  case when payload #>> '{venue,merchant,business_id}' ~ '\d{3,}'
       then upper(regexp_replace(btrim(payload #>> '{venue,merchant,business_id}'), '\s+', ' ', 'g')) end as legal_register_id,
  {{ clean_text("payload #>> '{venue,merchant,street_address}'") }} as legal_street,
  nullif(payload #>> '{venue,merchant,post_code}', '')     as legal_postcode,
  nullif(payload #>> '{venue,merchant,city}', '')          as legal_city,
  substring(payload #>> '{venue,description}' from '(DE ?\d{9})') as vat_number,
  (payload #>> '{venue_raw,location,coordinates,1}')::float8 as lat,
  (payload #>> '{venue_raw,location,coordinates,0}')::float8 as lon,
  (payload #>> '{venue,rating,score_raw}')::numeric(4,2)   as rating_value,
  (payload #>> '{venue,rating,volume}')::integer           as rating_count,
  (payload #>> '{venue_raw,price_range}')::smallint        as price_range,
  {{ cents("payload ->> 'order_minimum'") }}               as order_minimum,
  {{ cents("payload #>> '{venue,delivery_base_price}'") }} as delivery_base_fee,
  {{ cents("payload #>> '{venue,service_fee_estimate,min}'") }} as service_fee_min,
  {{ cents("payload #>> '{venue,service_fee_estimate,max}'") }} as service_fee_max,
  (payload #>> '{venue,self_delivery}')::boolean           as self_delivery,
  ops.jarr(payload #> '{venue_raw,food_tags}') as food_tags,
  ops.jarr(payload #> '{venue_raw,categories}') as categories,
  ops.jarr(payload #> '{venue,delivery_methods}') as delivery_methods,
  ops.jarr(payload #> '{venue_raw,allowed_payment_methods}') as payment_methods,
  payload #> '{venue_raw,opening_times}'                   as opening_times,
  payload #> '{venue,opening_times_schedule}'              as opening_times_display,
  payload #> '{venue,delivery_times_schedule}'             as delivery_times_display,
  payload #> '{venue,delivery_geo_range}'                  as delivery_area_geojson,
  (payload #>> '{venue_raw,is_wolt_plus}')::boolean        as wolt_plus,
  payload #>> '{venue,image_url}'                          as cover_image_url,
  payload #>> '{venue,brand_logo_image_url}'               as logo_url,
  payload                                                  as attributes
from src
